### ISSUE TITLE
Error building SSR application with input-mask imported - self is not defined

### ISSUE THREAD

**Issue by asithade** [ngneat/input-mask#89]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[ ] Other... Please describe:
</code></pre>

## Current behavior

When trying to build my SSR application, I get the following error returned: 
```bash
/Users/asitha/xxx/public/dist/xxx/server/main.js:125172
}(self, function () {
  ^

ReferenceError: self is not defined
    at Object.43641 (/Users/asitha/xxx/public/dist/xxx/server/main.js:125172:3)
    at /Users/asitha/xxx/public/dist/xxx/server/main.js:207873:39
    at Function.proto.<computed> (/Users/asitha/xxx/public/dist/xxx/server/main.js:205816:18)
    at __webpack_require__ (/Users/asitha/xxx/public/dist/xxx/server/main.js:470193:42)
    at Module.2105 (/Users/asitha/xxx/public/dist/xxx/server/main.js:448037:67)
    at /Users/asitha/xxx/public/dist/xxx/server/main.js:207873:39
    at Function.proto.<computed> (/Users/asitha/xxx/public/dist/xxx/server/main.js:205816:18)
    at __webpack_require__ (/Users/asitha/xxx/public/dist/xxx/server/main.js:470193:42)
    at Module.40228 (/Users/asitha/xxx/public/dist/xxx/server/main.js:2251:76)
    at /Users/asitha/xxx/public/dist/xxx/server/main.js:207873:39
```

Looking into that line of code, I see that it was the inputmask that in the dist file that was causing the issue: 
```javascript
/*!**************************************************!*\
  !*** ./node_modules/inputmask/dist/inputmask.js ***!
  \**************************************************/
/***/ ((module) => {

/*!
 * dist/inputmask
 * https://github.com/RobinHerbots/Inputmask
 * Copyright (c) 2010 - 2021 Robin Herbots
 * Licensed under the MIT license
 * Version: 5.0.7
 */
!function (e, t) {
  if (true) module.exports = t();else { var a, i; }
}(self, function () {
  return function () {
    "use strict";
```

I attempted to do the `isPlatformBrowser` check before calling `createMask` but the only way to fix it was to not import the module at all within the application. Also attempted to install the beta version of this package, but that didn't work either.

## Expected behavior

Able to build application with the package included in the imported modules.

## Environment

<pre><code>
Angular version: 14.2.7
    "@angular/animations": "^14.2.7",
    "@angular/cdk": "14.2.5",
    "@angular/common": "^14.2.7",
    "@angular/compiler": "^14.2.7",
    "@angular/core": "^14.2.7",
    "@angular/fire": "7.4.1",
    "@angular/flex-layout": "^14.0.0-beta.41",
    "@angular/forms": "^14.2.7",
    "@angular/material": "14.2.5",
    "@angular/platform-browser": "^14.2.7",
    "@angular/platform-browser-dynamic": "^14.2.7",
    "@angular/platform-server": "^14.2.7",
    "@angular/router": "^14.2.7",
    "@fortawesome/angular-fontawesome": "^0.11.0",
    "@fortawesome/fontawesome-svg-core": "^6.1.1",
    "@fortawesome/free-regular-svg-icons": "^6.1.1",
    "@fortawesome/free-solid-svg-icons": "^6.1.1",
    "@ngneat/input-mask": "^5.3.0-beta.1",

For Tooling issues:
- Node version: 16  
- Platform:  Mac

Others:

</code></pre>

**Comment by gtatakis** [comment]
I am facing the exact same issue. 

I have installed  "inputmask": "^5.0.8-beta.47", based on the following thread: https://github.com/RobinHerbots/Inputmask/issues/2661

but the issue remains 
Angular CLI: 13.1.4
Node: 18.11.0 (Unsupported)
Package Manager: npm 7.19.1
OS: darwin x64

Angular: 13.1.3
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1303.9
@angular-devkit/build-angular   13.3.9
@angular-devkit/core            13.3.9
@angular-devkit/schematics      13.1.4
@angular/cli                    13.1.4
@nguniversal/builders           13.1.1
@nguniversal/express-engine     13.1.1
@schematics/angular             13.1.4
rxjs                            7.4.0
typescript                      4.5.5

**Comment by shhdharmen** [comment]
Please create a repo to reproduce this issue.
