### ISSUE TITLE
Can't install in angular version 11.2.13

### ISSUE THREAD

**Issue by Hellogark** [ngneat/input-mask#90]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
[X] Other... Please describe: Installation problem
</code></pre>

## Current behavior

When installing with ng add @ngneat/input-mask

i get the next log 

Using package manager: yarn
✔ Found compatible package version: @ngneat/input-mask@4.1.1.
✔ Package information loaded.
✔ Package successfully installed.
    ✅️ Added "inputmask
    ✅️ Added "@types/inputmask
    � Installing packages...
Cannot read property 'kind' of undefined

after the undefined the instalation doesn't continue, if i install it manualy, it says this 
> @ngneat/input-mask@4.1.1" has unmet peer dependency "inputmask@^5.0.5". and doing ng serve, it throws this error 
An unhandled exception occurred: The target entry-point "@ngneat/input-mask" has missing dependencies:
 - inputmask

[error] Error: The target entry-point "@ngneat/input-mask" has missing dependencies:
 - inputmask

    at TargetedEntryPointFinder.findEntryPoints (C:\user\node_modules\@angular\compiler-cli\ngcc\src\entry_point_finder\targeted_entry_point_finder.js:40:23)
    at K:\kordataCliente\node_modules\@angular\compiler-cli\ngcc\src\execution\analyze_entry_points.js:29:41
    at SingleProcessExecutorSync.SingleProcessorExecutorBase.doExecute (C:\user\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:28:29)
    at K:\kordataCliente\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:59
    at SyncLocker.lock (C:\user\node_modules\@angular\compiler-cli\ngcc\src\locking\sync_locker.js:34:24)
    at SingleProcessExecutorSync.execute (C:\user\node_modules\@angular\compiler-cli\ngcc\src\execution\single_process_executor.js:57:27)
    at Object.mainNgcc (C:\user\node_modules\@angular\compiler-cli\ngcc\src\main.js:74:25)
    at Object.process (C:\user\node_modules\@angular\compiler-cli\ngcc\index.js:29:23)
    at NgccProcessor.processModule (C:\user\node_modules\@ngtools\webpack\src\ngcc_processor.js:163:16)
    at K:\kordataCliente\node_modules\@ngtools\webpack\src\ivy\host.js:109:18
    at K:\kordataCliente\node_modules\@ngtools\webpack\src\ivy\host.js:39:24
    at Array.map (<anonymous>)
    at Object.host.resolveModuleNames (C:\user\node_modules\@ngtools\webpack\src\ivy\host.js:37:32)
    at actualResolveModuleNamesWorker (C:\user\node_modules\typescript\lib\typescript.js:102904:133)
    at resolveModuleNamesWorker (C:\user\node_modules\typescript\lib\typescript.js:103126:26)
    at resolveModuleNamesReusingOldState (C:\user\node_modules\typescript\lib\typescript.js:103200:24)

## Expected behavior

I want get installed with this version
## Minimal reproduction of the problem with instructions
"@angular/core": "^11.2.13"
ng add @ngneat/input-mask
## Environment

<pre><code>
Angular version: 11.2.13

**Comment by shhdharmen** [comment]
Minimum version support is 11.2.7
